// quotes.js

const motivationalQuotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "It does not matter how slowly you go, as long as you do not stop. - Confucius",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "It always seems impossible until it's done. - Nelson Mandela",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "Our greatest glory is not in never falling, but in rising every time we fall. - Confucius",
    "In the middle of difficulty lies opportunity. - Albert Einstein",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. – Unknown",
    "It’s not whether you get knocked down, it’s whether you get up. – Inspirational Quote By Vince Lombardi",
	"The harder you work for something, the greater you'll feel when you achieve it. - Unknown",
    "Success is not just about making money, it's about making a difference. - Unknown",
    "Your life only gets better when you do. Work on yourself and the rest will follow. - Unknown",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The distance between your dreams and reality is called action. - Unknown",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
    "You are braver than you believe, stronger than you seem, and smarter than you think. - A.A. Milne",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently. - Marie Forleo",
    "Don’t wish it were easier; wish you were better. - Jim Rohn",
    "Your attitude, not your aptitude, will determine your altitude. - Zig Ziglar",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "You can’t go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "The best way to predict the future is to invent it. - Alan Kay",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It’s not about how bad you want it. It’s about how hard you’re willing to work for it. - Unknown",
    "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "If you believe in yourself and have dedication and pride - and never quit, you'll be a winner. - Paul Bryant",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty. - Winston Churchill",
    "Great things never come from comfort zones. - Neil Strauss",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "Success is not the absence of failure; it’s the persistence through failure. - Aisha Tyler",
    "I never dreamed about success, I worked for it. - Estee Lauder",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "You don’t have to be perfect to be amazing. - Unknown",
    "Dream it. Believe it. Build it. - Unknown",
    "It does not matter how slowly you go, as long as you do not stop. – Confucius",
    "Opportunities don’t happen, you create them. - Chris Grosser",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "Don’t stop when you’re tired. Stop when you’re done. - Unknown",
    "If you are not willing to risk the usual, you will have to settle for the ordinary. - Jim Rohn",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "It does not matter how slowly you go as long as you do not stop. – Confucius",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Don’t let yesterday take up too much of today. – Will Rogers",
    "You learn more from failure than from success. Don’t let it stop you. Failure builds character. – Unknown",
    "It’s not whether you get knocked down, it’s whether you get up. – Inspirational Quote By Vince Lombardi",
    "Success is not just about making money, it's about making a difference. - Unknown",
    "Your life only gets better when you do. Work on yourself and the rest will follow. - Unknown",
    "Don't be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "The distance between your dreams and reality is called action. - Unknown",
    "Failure is the condiment that gives success its flavor. - Truman Capote",
	"Believe you can and you're halfway there. - Theodore Roosevelt",
	"It always seems impossible until it's done. - Nelson Mandela",
	"Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
	"Don't watch the clock; do what it does. Keep going. - Sam Levenson",
	"You miss 100% of the shots you don't take. - Wayne Gretzky",
	"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
	"You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
	"The only way to do great work is to love what you do. - Steve Jobs",
	"Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
	"You get in life what you have the courage to ask for. - Oprah Winfrey",
	"The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
	"Hustle beats talent when talent doesn't hustle. - Gary Vaynerchuk",
	"Do something today that your future self will thank you for. - Unknown",
	"You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
	"The best way to predict your future is to create it. - Abraham Lincoln",
	"The biggest risk is not taking any risk... - Mark Zuckerberg",
	"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
	"You are stronger than you seem, braver than you believe, and smarter than you think. - Christopher Robin",
	"The only person you should try to be better than is the person you were yesterday. - Anonymous",
	"You don't have to be perfect to be amazing. - Anonymous",
	"Don't let yesterday take up too much of today. - Cherokee Proverb",
	"You are capable of amazing things. - Anonymous",
	"Believe in yourself, take the leap of faith and watch the universe conspire to make your dreams a reality. - Rumi",
	"A year from now you will wish you had started today. - Karen Lamb",
	"You don't need a title to be a leader. - Anonymous",
	"Don't watch the clock; do what it does. Keep going. - Sam Levenson",
	"What lies within us is greater than what lies before us. - Anonymous",
	"You are the architect of your own destiny. - Anonymous",
	"The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
	"You are never too young to make a difference. - Anonymous",
	"Success is not about being better than anyone else, it's about being better than you used to be. - Anonymous",
	"You get what you work for, not what you wish for. - Anonymous",
	"The only thing holding you back is your own doubt. - Anonymous",
	"You are the master of your destiny. - Anonymous",
	"The best revenge is massive success. - Frank Sinatra",
	"The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
	"Do not let what you cannot do interfere with what you can do. - John Wooden",
	"The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
	"Do something worth remembering. - Anonymous",
	"The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
	"You are the sum of your choices. - Anonymous",
	"Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
	"You are stronger than you seem. - Anonymous",
	"The only thing that interferes with my learning is my education. - Albert Einstein",
	"The best way to get started is to quit talking and begin doing. - Walt Disney",
	"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
	"You are the driver of your own destiny. - Anonymous",
	"The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
	"You are the creator of your own destiny. - Anonymous",
	"The only thing holding you back is your own mind. - Anonymous",
	"You are the master of your own fate. - Anonymous",
	"The only thing we have to fear is fear itself — and spiders. - Anonymous",
	"Don't watch the clock; do what it does. Keep going. - Sam Levenson",
	"You miss 100% of the shots you don't take. - Wayne Gretzky",
	"I have not failed. I've just found 10,000 ways that won't work. - Thomas Edison",
	"You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
	"The only way to do great work is to love what you do. - Steve Jobs",
	"Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt",
	"You get in life what you have the courage to ask for. - Oprah Winfrey",
	"The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
	"Hustle beats talent when talent doesn't hustle. - Gary Vaynerchuk",
	"Do something today that your future self will thank you for. - Unknown",
	"You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
	"The best way to predict your future is to create it. - Abraham Lincoln",
	"The biggest risk is not taking any risk... - Mark Zuckerberg",
	"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
	"You are stronger than you seem, braver than you believe, and smarter than you think. - Christopher Robin",
	"The only person you should try to be better than is the person you were yesterday. - Anonymous",
	"You don't have to be perfect to be amazing. - Anonymous",
	"Don't let yesterday take up too much of today. - Cherokee Proverb",
	"You are capable of amazing things. - Anonymous",
	"Believe in yourself, take the leap of faith and watch the universe conspire to make your dreams a reality. - Rumi",
	"A year from now you will wish you had started today. - Karen Lamb",
	"You don't need a title to be a leader. - Anonymous",
	"What lies within us is greater than what lies before us. - Anonymous",
	"You are the architect of your own destiny. - Anonymous",
	"The only thing necessary for the triumph of evil is for good men to do nothing. - Edmund Burke",
	"You are never too young to make a difference. - Anonymous",
	"Success is not about being better than anyone else, it's about being better than you used to be. - Anonymous",
	"You get what you work for, not what you wish for. - Anonymous",
	"The only thing holding you back is your own doubt. - Anonymous",
	"You are the master of your destiny. - Anonymous",
	"The best revenge is massive success. - Frank Sinatra",
	"The only thing we have to fear is fear itself. - Franklin D. Roosevelt",
	"Do not let what you cannot do interfere with what you can do. - John Wooden",
	"The greatest glory in living lies not in never falling, but in rising every time we fall. - Nelson Mandela",
	"Do something worth remembering. - Anonymous",
	"The biggest adventure you can take is to live the life of your dreams. - Oprah Winfrey",
	"You are the sum of your choices. - Anonymous",
	"Keep going. - Anonymous",
	"Stay focused. - Anonymous",
	"Keep pushing. - Anonymous",
	"Stay positive. - Anonymous",
	"Keep learning. - Anonymous",
	"Stay humble. - Anonymous",
	"Keep growing. - Anonymous",
	"Stay kind. - Anonymous",
	"Keep shining. - Anonymous",
	"Stay amazing. - Anonymous",
	"Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
	"Expect more, achieve more. - William Ward",
	"Motivation is what gets you started. Habit is what keeps you going. - Jim Rohn",
	"Excellence is not a destination; it is a continuous journey that never ends. - Brian Tracy",
	"Success is not final; failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
	"You don't have to be great to start, but you have to start to be great. - Zig Ziglar",
	"The best way to get started is to quit talking and begin doing. - Walt Disney",
	"The only thing holding you back is your own mind. - Anonymous",
	"You are the creator of your own destiny. - Anonymous",
	"The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
	"You are the driver of your own destiny. - Anonymous",  
];


export function getRandomQuote() {
    const randomIndex = Math.floor(Math.random() * motivationalQuotes.length);
    return motivationalQuotes[randomIndex];
}

